# Generated by Django 5.2.8 on 2025-11-19 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0003_remove_pedido_usuario_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionWebpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('orden_compra', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='INICIADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='carrito.pedido')),
            ],
        ),
    ]
