# Generated by Django 5.2.5 on 2025-11-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_perfilusuario_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
