# Generated by Django 5.2.8 on 2025-11-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
