# Generated by Django 5.2.8 on 2025-11-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='productos/'),
            preserve_default=False,
        ),
    ]
