# Generated by Django 5.2.5 on 2025-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_perfilusuario_rut_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
