# Generated by Django 5.2.8 on 2025-11-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventafisica',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
